### ISSUE TITLE
Not working in swift 3

### ISSUE THREAD

**Issue by chinmaykdas** [sua8051/JavaScriptInterface#1]
Please update the repository for swift 3.

**Comment by sua8051** [comment]
Dear,

The project is already in Swift 3 (xcode 8.2).

Thanks,
Sua

**Comment by suale-dev** [comment]
@chinmaykdas updated Swift 3.

**Comment by chinmaykdas** [comment]
Thanks @sua8051

**Comment by chinmaykdas** [comment]
Thanks @sua8051
